# Oracle Database Connection Properties
db.user=user
db.password=pwd
db.dsn=SVJC-DES-ORA19.TTEC.ES:1521/Oracle
# If you get DPY-3010, specify the path to your Oracle Instant Client (e.g., C:\oracle\instantclient_21_3)
db.client_path=E:\oracle11\product\11.2.0\client_1\BIN
# For Thin mode, DSN can be host:port/service_name or a TNS connect descriptor